version: '3'

services:
  web:
    build: .
    ports:
      - "3000:5000" ##  map port 3000 on host machine to port 5000 in the Docker container.
    environment:
      DB_URL: "postgresql://postgres:secret123@postgres:5432/uber"
    depends_on:
      - postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: uber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: