"""Add user_sid to rides

Revision ID: fc767763acc7
Revises: ea4e67fb3237
Create Date: 2024-05-26 23:30:12.421591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc767763acc7'
down_revision = 'ea4e67fb3237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_sid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rides', schema=None) as batch_op:
        batch_op.drop_column('user_sid')

    # ### end Alembic commands ###
