"""Create Cab table

Revision ID: 047a3ae10e78
Revises: 567565d5a7f1
Create Date: 2024-04-24 00:27:56.458344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047a3ae10e78'
down_revision = '567565d5a7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cabs')
    # ### end Alembic commands ###
