"""Add fields to cabs

Revision ID: e72aabd6f6b6
Revises: 047a3ae10e78
Create Date: 2024-05-31 23:29:05.523118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72aabd6f6b6'
down_revision = '047a3ae10e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cabs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('make', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cabs', schema=None) as batch_op:
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('make')

    # ### end Alembic commands ###
